version: 2.1
orbs:
  utils: arrai/utils@1.8.0
  flake8: arrai/flake8@11.0.1
executors:
  python36:
    environment:
      LANG: C.UTF-8
    docker:
      - image: cimg/python:3.6
  python37:
    environment:
      LANG: C.UTF-8
    docker:
      - image: cimg/python:3.7
  python38:
    environment:
      LANG: C.UTF-8
    docker:
      - image: cimg/python:3.8
  python39:
    environment:
      LANG: C.UTF-8
    docker:
      - image: cimg/python:3.9
jobs:
  pythontests:
    parameters:
      executor:
        description: "Execution environment for the test job."
        type: executor
        default: python37
    executor: <<parameters.executor>>
    steps:
      - checkout
      - run:
          name: Install additional packages
          command: |
            sudo apt-get update
            sudo apt-get install rsync
      - utils/add_ssh_config:
          host: "docs"
          hostname: ${DOCS_HOST}
          port: ${DOCS_PORT}
          user: ${DOCS_USER}
      - utils/make_status_shield:
          status: running
          color: lightblue
      - run: pip install -r requirements.txt -r test_requirements.txt | cat; test ${PIPESTATUS[0]} -eq 0
      - run:
          name: Run tests
          command: |
            python setup.py test
            pip install pip==9.0.3
            python setup.py test
      - run:
          when: always
          command: |
            coverage html
            coverage report | tail -1 | awk '{print substr($NF, 1, length($NF)-1)}' >> ~/.coveragep
      - utils/rsync_folder:
          when: always
          folder: ./htmlcov/
          remote_folder: ${CIRCLE_BRANCH}/htmlcov_${CIRCLE_JOB}
          host: docs
      - utils/make_coverage_shield:
          when: always
          link: "https://${DOCS_HOST}/${CIRCLE_PROJECT_REPONAME}/artifacts/${CIRCLE_BRANCH}/htmlcov_${CIRCLE_JOB}/"
      - utils/rsync_file:
          when: always
          file: /tmp/coverage.svg
          remote_file: ${CIRCLE_BRANCH}/${CIRCLE_JOB}.coverage.svg
          host: docs
      - run:
          when: always
          command: pip freeze > ~/pip.freeze
      - utils/rsync_file:
          when: always
          file: ~/pip.freeze
          remote_file: ${CIRCLE_BRANCH}/${CIRCLE_JOB}.freeze
          host: docs
      - utils/make_status_shield:
          when: on_success
          status: passed
          color: brightgreen
      - utils/make_status_shield:
          when: on_fail
          status: failed
          color: red
      - utils/rsync_file:
          when: always
          file: ~/status.svg
          remote_file: ${CIRCLE_BRANCH}/${CIRCLE_JOB}.svg
          host: docs
workflows:
  test:
    jobs:
      - pythontests:
          name: python36
          executor: python36
          context: arrai-global
      - pythontests:
          name: python37
          executor: python37
          context: arrai-global
      - pythontests:
          name: python38
          executor: python38
          context: arrai-global
      - pythontests:
          name: python39
          executor: python39
          context: arrai-global
      - flake8/flake8:
          name: flake8
          context: arrai-global
          wd: .
